// Generated by scripts/gen-schemas.ts from spec/api.openapi.yaml. Do not edit.
export const apiVersion = "0.1.0";

export const schemas = {
	"Point": {
		"type": "object",
		"additionalProperties": false,
		"required": [
			"lat",
			"lon"
		],
		"properties": {
			"lat": {
				"type": "number",
				"minimum": -90,
				"maximum": 90
			},
			"lon": {
				"type": "number",
				"minimum": -180,
				"maximum": 180
			}
		}
	},
	"Stop": {
		"type": "object",
		"additionalProperties": false,
		"required": [
			"id",
			"name",
			"point",
			"feedId"
		],
		"properties": {
			"id": {
				"type": "string"
			},
			"name": {
				"type": "string"
			},
			"point": {
				"$ref": "#/components/schemas/Point"
			},
			"feedId": {
				"type": "string",
				"description": "Dataset id from config/sources.yaml, e.g. tte, ttu, trenitalia"
			},
			"publicCode": {
				"type": "string"
			}
		}
	},
	"Destination": {
		"type": "object",
		"additionalProperties": false,
		"required": [
			"id",
			"name",
			"category",
			"entrance",
			"description",
			"infoUrl",
			"checkedAt"
		],
		"properties": {
			"id": {
				"type": "string"
			},
			"name": {
				"type": "string"
			},
			"category": {
				"type": "string"
			},
			"entrance": {
				"$ref": "#/components/schemas/Point"
			},
			"description": {
				"type": "string",
				"maxLength": 500
			},
			"infoUrl": {
				"type": "string",
				"format": "uri"
			},
			"checkedAt": {
				"type": "string",
				"format": "date"
			},
			"accessNotes": {
				"type": "string"
			}
		}
	},
	"PlaceMatch": {
		"type": "object",
		"additionalProperties": false,
		"required": [
			"kind",
			"name",
			"point"
		],
		"properties": {
			"kind": {
				"type": "string",
				"enum": [
					"stop",
					"address",
					"place"
				]
			},
			"name": {
				"type": "string"
			},
			"point": {
				"$ref": "#/components/schemas/Point"
			},
			"stopId": {
				"type": "string",
				"description": "Present for kind=stop"
			},
			"feedId": {
				"type": "string",
				"description": "Present for kind=stop"
			},
			"area": {
				"type": "string",
				"description": "Municipality or locality",
				"when known": null
			}
		}
	},
	"SearchRequest": {
		"type": "object",
		"additionalProperties": false,
		"required": [
			"departAfter",
			"returnBy"
		],
		"oneOf": [
			{
				"required": [
					"originStopId"
				]
			},
			{
				"required": [
					"originPoint"
				]
			}
		],
		"properties": {
			"originStopId": {
				"type": "string",
				"minLength": 1,
				"maxLength": 200
			},
			"originPoint": {
				"$ref": "#/components/schemas/Point"
			},
			"originName": {
				"type": "string",
				"maxLength": 80,
				"description": "Label of the origin shown in itineraries when it is a point"
			},
			"departAfter": {
				"type": "string",
				"format": "date-time"
			},
			"returnBy": {
				"type": "string",
				"format": "date-time"
			},
			"maxJourneyMinutes": {
				"type": "integer",
				"minimum": 30,
				"maximum": 180,
				"default": 90
			},
			"minStayMinutes": {
				"type": "integer",
				"minimum": 30,
				"maximum": 480,
				"default": 120
			},
			"maxWalkMinutes": {
				"type": "integer",
				"minimum": 5,
				"maximum": 30,
				"default": 20
			},
			"maxTransfers": {
				"type": "integer",
				"minimum": 0,
				"maximum": 2,
				"default": 1
			}
		}
	},
	"SearchResponse": {
		"type": "object",
		"additionalProperties": false,
		"required": [
			"status",
			"dataVersion",
			"generatedAt",
			"normalizedRequest",
			"catalogCount",
			"evaluatedCount",
			"warnings",
			"proposals"
		],
		"properties": {
			"status": {
				"type": "string",
				"enum": [
					"complete",
					"partial"
				],
				"description": "complete = catalogue processed without detected errors or truncation, not an exhaustive enumeration of every possible route.\n"
			},
			"dataVersion": {
				"type": "string"
			},
			"generatedAt": {
				"type": "string",
				"format": "date-time"
			},
			"normalizedRequest": {
				"$ref": "#/components/schemas/SearchRequest"
			},
			"catalogCount": {
				"type": "integer",
				"minimum": 0,
				"maximum": 24
			},
			"evaluatedCount": {
				"type": "integer",
				"minimum": 0,
				"maximum": 24,
				"description": "Destinations with both profiles processed successfully"
			},
			"warnings": {
				"type": "array",
				"uniqueItems": true,
				"items": {
					"type": "string",
					"enum": [
						"PARTIAL_TIMEOUT",
						"PARTIAL_UPSTREAM_ERROR",
						"PARTIAL_TRUNCATED",
						"DATA_CHECK_OVERDUE"
					]
				}
			},
			"proposals": {
				"type": "array",
				"maxItems": 24,
				"items": {
					"$ref": "#/components/schemas/Proposal"
				}
			}
		}
	},
	"Proposal": {
		"type": "object",
		"additionalProperties": false,
		"required": [
			"destinationId",
			"outbound",
			"inbound",
			"staySeconds",
			"returnStatus"
		],
		"properties": {
			"destinationId": {
				"type": "string"
			},
			"outbound": {
				"$ref": "#/components/schemas/Journey"
			},
			"inbound": {
				"$ref": "#/components/schemas/Journey"
			},
			"backupInbound": {
				"$ref": "#/components/schemas/Journey"
			},
			"staySeconds": {
				"type": "integer",
				"minimum": 0
			},
			"returnStatus": {
				"type": "string",
				"enum": [
					"later_option_found",
					"no_later_option_found"
				],
				"description": "later_option_found requires a valid backupInbound"
			}
		}
	},
	"Journey": {
		"type": "object",
		"additionalProperties": false,
		"required": [
			"startTime",
			"endTime",
			"durationSeconds",
			"walkingBudgetSeconds",
			"transfers",
			"legs"
		],
		"properties": {
			"startTime": {
				"type": "string",
				"format": "date-time"
			},
			"endTime": {
				"type": "string",
				"format": "date-time"
			},
			"durationSeconds": {
				"type": "integer",
				"minimum": 0
			},
			"walkingBudgetSeconds": {
				"type": "integer",
				"minimum": 0,
				"description": "Conservative sum of WALK segments, including any engine margins"
			},
			"transfers": {
				"type": "integer",
				"minimum": 0,
				"maximum": 2
			},
			"legs": {
				"type": "array",
				"minItems": 1,
				"items": {
					"$ref": "#/components/schemas/Leg"
				}
			}
		}
	},
	"Leg": {
		"type": "object",
		"additionalProperties": false,
		"required": [
			"mode",
			"from",
			"to",
			"startTime",
			"endTime",
			"durationSeconds"
		],
		"properties": {
			"mode": {
				"type": "string",
				"description": "Mode normalised from MOTIS; WALK for walking"
			},
			"from": {
				"$ref": "#/components/schemas/Place"
			},
			"to": {
				"$ref": "#/components/schemas/Place"
			},
			"startTime": {
				"type": "string",
				"format": "date-time"
			},
			"endTime": {
				"type": "string",
				"format": "date-time"
			},
			"durationSeconds": {
				"type": "integer",
				"minimum": 0
			},
			"routeName": {
				"type": "string"
			},
			"headsign": {
				"type": "string"
			},
			"tripId": {
				"type": "string",
				"description": "Opaque identifier including the service date"
			},
			"geometry": {
				"$ref": "#/components/schemas/EncodedPolyline",
				"description": "Optional; decode with the declared precision"
			}
		}
	},
	"Place": {
		"type": "object",
		"additionalProperties": false,
		"required": [
			"name",
			"point"
		],
		"properties": {
			"name": {
				"type": "string"
			},
			"point": {
				"$ref": "#/components/schemas/Point"
			},
			"stopId": {
				"type": "string"
			}
		}
	},
	"EncodedPolyline": {
		"type": "object",
		"additionalProperties": false,
		"required": [
			"points",
			"precision"
		],
		"properties": {
			"points": {
				"type": "string"
			},
			"precision": {
				"type": "integer",
				"minimum": 0,
				"maximum": 8
			}
		}
	},
	"DataStatus": {
		"type": "object",
		"additionalProperties": false,
		"required": [
			"status",
			"dataVersion",
			"timezone",
			"availableFrom",
			"availableTo",
			"sources",
			"limitations"
		],
		"properties": {
			"status": {
				"type": "string",
				"enum": [
					"current",
					"warning",
					"unavailable"
				]
			},
			"dataVersion": {
				"type": [
					"string",
					"null"
				]
			},
			"timezone": {
				"type": "string",
				"const": "Europe/Rome"
			},
			"availableFrom": {
				"type": [
					"string",
					"null"
				],
				"format": "date"
			},
			"availableTo": {
				"type": [
					"string",
					"null"
				],
				"format": "date"
			},
			"sources": {
				"type": "array",
				"items": {
					"type": "object",
					"additionalProperties": false,
					"required": [
						"id",
						"publisher",
						"checkedAt",
						"sourceUrl",
						"licenseUrl"
					],
					"properties": {
						"id": {
							"type": "string"
						},
						"publisher": {
							"type": "string"
						},
						"checkedAt": {
							"type": [
								"string",
								"null"
							],
							"format": "date-time"
						},
						"feedVersion": {
							"type": "string"
						},
						"sourceUrl": {
							"type": "string",
							"format": "uri"
						},
						"licenseUrl": {
							"type": "string",
							"format": "uri"
						}
					}
				}
			},
			"limitations": {
				"type": "array",
				"items": {
					"type": "string"
				}
			}
		}
	},
	"Problem": {
		"type": "object",
		"additionalProperties": false,
		"required": [
			"code",
			"message"
		],
		"properties": {
			"code": {
				"type": "string",
				"enum": [
					"INVALID_REQUEST",
					"UNKNOWN_ORIGIN",
					"ORIGIN_NOT_COVERED",
					"DATE_NOT_COVERED",
					"DATA_UNAVAILABLE",
					"REQUEST_TOO_LARGE",
					"RATE_LIMITED",
					"ROUTING_UNAVAILABLE"
				]
			},
			"message": {
				"type": "string",
				"maxLength": 250
			}
		}
	}
} as const;
