/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/stops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search physical stops of the active data snapshot */
        get: operations["findStops"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search stops, addresses and places to start from
         * @description Geocoding runs on the service's own OpenStreetMap extract; no third-party geocoder.
         */
        get: operations["findPlaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reachability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview of the stops one can reach by a given time
         * @description Earliest arrival at each stop leaving the origin not before departAfter, initial waiting included (one-to-all). It is a preview for the map: it checks no return, no destination entrance and no stay, and it never produces proposals.
         */
        get: operations["getReachability"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/destinations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Published catalogue, at most 24 destinations in v0.1 */
        get: operations["listDestinations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Propose outbound journey, stay and return
         * @description Validate Europe/Rome, same day, 06:00-23:00 range, 2-16 hour window, no past dates and available coverage. For a search today, departAfter cannot precede the current instant. Pin the data snapshot for the whole request. At most 12 seconds of processing.
         */
        post: operations["searchTrips"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public coverage and provenance */
        get: operations["getDataStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Point: {
            lat: number;
            lon: number;
        };
        Stop: {
            id: string;
            name: string;
            point: components["schemas"]["Point"];
            /** @description Dataset id from config/sources.yaml, e.g. tte, ttu, trenitalia */
            feedId: string;
            publicCode?: string;
        };
        Destination: {
            id: string;
            name: string;
            category: string;
            entrance: components["schemas"]["Point"];
            description: string;
            /** Format: uri */
            infoUrl: string;
            /** Format: date */
            checkedAt: string;
            accessNotes?: string;
        };
        Reachability: {
            dataVersion: string;
            /** Format: date-time */
            departAfter: string;
            minutes: number;
            places: {
                name: string;
                point: components["schemas"]["Point"];
                stopId?: string;
                /** @description Arrival minus departAfter */
                minutes: number;
                transfers: number;
            }[];
        };
        PlaceMatch: {
            /** @enum {string} */
            kind: "stop" | "address" | "place";
            name: string;
            point: components["schemas"]["Point"];
            /** @description Present for kind=stop */
            stopId?: string;
            /** @description Present for kind=stop */
            feedId?: string;
            /** @description Municipality or locality */
            area?: string;
        };
        SearchRequest: {
            originStopId?: string;
            originPoint?: components["schemas"]["Point"];
            /** @description Label of the origin shown in itineraries when it is a point */
            originName?: string;
            /** Format: date-time */
            departAfter: string;
            /** Format: date-time */
            returnBy: string;
            /** @default 90 */
            maxJourneyMinutes: number;
            /** @default 120 */
            minStayMinutes: number;
            /** @default 20 */
            maxWalkMinutes: number;
            /** @default 1 */
            maxTransfers: number;
        } & (unknown | unknown);
        SearchResponse: {
            /**
             * @description complete = catalogue processed without detected errors or truncation, not an exhaustive enumeration of every possible route.
             * @enum {string}
             */
            status: "complete" | "partial";
            dataVersion: string;
            /** Format: date-time */
            generatedAt: string;
            normalizedRequest: components["schemas"]["SearchRequest"];
            catalogCount: number;
            /** @description Destinations with both profiles processed successfully */
            evaluatedCount: number;
            warnings: ("PARTIAL_TIMEOUT" | "PARTIAL_UPSTREAM_ERROR" | "PARTIAL_TRUNCATED" | "DATA_CHECK_OVERDUE")[];
            proposals: components["schemas"]["Proposal"][];
        };
        Proposal: {
            destinationId: string;
            outbound: components["schemas"]["Journey"];
            inbound: components["schemas"]["Journey"];
            backupInbound?: components["schemas"]["Journey"];
            staySeconds: number;
            /**
             * @description later_option_found requires a valid backupInbound
             * @enum {string}
             */
            returnStatus: "later_option_found" | "no_later_option_found";
        };
        Journey: {
            /** Format: date-time */
            startTime: string;
            /** Format: date-time */
            endTime: string;
            durationSeconds: number;
            /** @description Conservative sum of WALK segments, including any engine margins */
            walkingBudgetSeconds: number;
            transfers: number;
            legs: components["schemas"]["Leg"][];
        };
        Leg: {
            /** @description Mode normalised from MOTIS; WALK for walking */
            mode: string;
            from: components["schemas"]["Place"];
            to: components["schemas"]["Place"];
            /** Format: date-time */
            startTime: string;
            /** Format: date-time */
            endTime: string;
            durationSeconds: number;
            routeName?: string;
            headsign?: string;
            /** @description Opaque identifier including the service date */
            tripId?: string;
            /** @description Optional; decode with the declared precision */
            geometry?: components["schemas"]["EncodedPolyline"];
        };
        Place: {
            name: string;
            point: components["schemas"]["Point"];
            stopId?: string;
        };
        EncodedPolyline: {
            points: string;
            precision: number;
        };
        DataStatus: {
            /** @enum {string} */
            status: "current" | "warning" | "unavailable";
            dataVersion: string | null;
            /** @constant */
            timezone: "Europe/Rome";
            /** Format: date */
            availableFrom: string | null;
            /** Format: date */
            availableTo: string | null;
            sources: {
                id: string;
                publisher: string;
                /** Format: date-time */
                checkedAt: string | null;
                feedVersion?: string;
                /** Format: uri */
                sourceUrl: string;
                /** Format: uri */
                licenseUrl: string;
            }[];
            limitations: string[];
        };
        Problem: {
            /** @enum {string} */
            code: "INVALID_REQUEST" | "UNKNOWN_ORIGIN" | "ORIGIN_NOT_COVERED" | "DATE_NOT_COVERED" | "DATA_UNAVAILABLE" | "REQUEST_TOO_LARGE" | "RATE_LIMITED" | "ROUTING_UNAVAILABLE";
            message: string;
        };
    };
    responses: {
        /** @description Readable error; no engine internals */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Request limit or capacity temporarily exhausted */
        RateLimit: {
            headers: {
                "Retry-After": number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description Language of names, descriptions and limitations (default it) */
        Lang: "it" | "en";
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    findStops: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description At most 20 stops; opaque identifiers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stop"][];
                };
            };
            400: components["responses"]["Problem"];
            429: components["responses"]["RateLimit"];
            503: components["responses"]["Problem"];
        };
    };
    findPlaces: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description At most 20 matches, best first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceMatch"][];
                };
            };
            400: components["responses"]["Problem"];
            429: components["responses"]["RateLimit"];
            503: components["responses"]["Problem"];
        };
    };
    getReachability: {
        parameters: {
            query: {
                /** @description A stop id or "lat,lon" */
                from: string;
                departAfter: string;
                minutes: number;
                maxTransfers?: number;
                maxWalkMinutes?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reachable stops, nearest in time first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reachability"];
                };
            };
            400: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["RateLimit"];
            503: components["responses"]["Problem"];
        };
    };
    listDestinations: {
        parameters: {
            query?: {
                /** @description Language of names, descriptions and limitations (default it) */
                lang?: components["parameters"]["Lang"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Draft destinations are excluded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Destination"][];
                };
            };
            503: components["responses"]["Problem"];
        };
    };
    searchTrips: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "originStopId": "tte_1",
                 *       "departAfter": "2026-09-26T08:00:00+02:00",
                 *       "returnBy": "2026-09-26T18:00:00+02:00",
                 *       "maxJourneyMinutes": 90,
                 *       "minStayMinutes": 120,
                 *       "maxWalkMinutes": 20,
                 *       "maxTransfers": 1
                 *     }
                 */
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description A complete search may be empty. A partial search must report causes and counts; it does not justify conclusions of unreachability. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            400: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["RateLimit"];
            /** @description No destination could be processed because of a technical failure or unusable data */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getDataStatus: {
        parameters: {
            query?: {
                /** @description Language of names, descriptions and limitations (default it) */
                lang?: components["parameters"]["Lang"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Data status, also when routing is suspended */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataStatus"];
                };
            };
        };
    };
}
