// Generates src/lib/api/schemas.gen.ts from the OpenAPI contract so the server can
// validate payloads at runtime without parsing YAML. Run through `npm run gen:api`.
import { readFileSync, writeFileSync } from 'node:fs';
import { parse } from 'yaml';

const spec = parse(readFileSync('spec/api.openapi.yaml', 'utf8'));
const schemas = spec?.components?.schemas;
if (!schemas || typeof schemas !== 'object') {
	throw new Error('spec/api.openapi.yaml has no components.schemas');
}

const output = `// Generated by scripts/gen-schemas.ts from spec/api.openapi.yaml. Do not edit.
export const apiVersion = ${JSON.stringify(spec.info.version)};

export const schemas = ${JSON.stringify(schemas, null, '\t')} as const;
`;

writeFileSync('src/lib/api/schemas.gen.ts', output);
